# Generated by Django 4.1.7 on 2023-04-02 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категорія таблиці',
                'verbose_name_plural': 'Категорії таблиць',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('owner', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('place', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('asset_category', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('threat', models.TextField(blank=True, default=None, null=True)),
                ('source_of_threat', models.TextField(blank=True, default=None, null=True)),
                ('mechanism', models.TextField(blank=True, default=None, null=True)),
                ('table_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tablecategory')),
            ],
            options={
                'verbose_name': 'Таблиця',
                'verbose_name_plural': 'Таблиці',
            },
        ),
    ]
